source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

xcodeproj '../AdsumReader.xcodeproj'
workspace 'AdsumReader'

pod 'ActionSheetPicker-3.0'
#pod 'MLPAutoCompleteTextField'
#pod 'MLPAutoCompleteTextField', :git => 'https://github.com/EddyBorja/MLPAutoCompleteTextField.git'